Source/QNews.Admin/Controllers/AlbumController.cs
using QNews.Data.Admin;
using QNews.Models;
using QNews.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Security.Application;

namespace QNews.Admin.Controllers
{
    public class AlbumController : BaseController
    {
        AlbumDA _AlbumDA = new AlbumDA("#");

        public ActionResult Details(int id)
        {
            AlbumDA albumDA = new AlbumDA();
            var model = albumDA.getById(id);
            ViewBag.AllStatus = albumDA.getAllStatusSimple();
            ViewBag.AllUser = albumDA.getAllUserSimple();
            return View(model);
        }


        public ActionResult AutoComplete()
        {
            if (DoAction == ActionType.Add) //Nếu thêm mới
            {
                JsonMessage msg = new JsonMessage();
                string SearchValue = Request["Values"];
                if (string.IsNullOrEmpty(SearchValue))
                {
                    msg = new JsonMessage()
                    {
                        Erros = true,
                        Message = "Bạn phải nhập tên nội dung"
                    };
                }
                else
                {
                    var _Album = _AlbumDA.getByName(SearchValue);
                    if (_Album == null)
                    {
                        msg = new JsonMessage()
                        {
                            Erros = true,
                            Message = "nội dung không tồn tại trong hệ thống"
                        };
                    }
                    else
                    {
                        msg = new JsonMessage()
                        {
                            Erros = false,
                            ID = _Album.ID.ToString(),
                            Message = _Album.Title
                        };
                    }
                }
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            else //Nếu xem từ khóa
            {
                string query = Request["query"];
                var ltsResults = _AlbumDA.GetListSimpleByAutoComplete(query, 10);
                AutoCompleteItem ResulValues = new AutoCompleteItem()
                {
                    query = query,
                    data = ltsResults.Select(o => o.ID.ToString()).ToList(),
                    suggestions = ltsResults.Select(o => o.Title).ToList()
                };
                return Json(ResulValues, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Trang chủ, index. Load ra grid dưới dạng ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            AlbumTopicDA albumTypeDA = new AlbumTopicDA();
            ViewBag.AllCategory = albumTypeDA.getAllListSimple();
            ViewBag.AllStatus = albumTypeDA.getAllStatusSimple();
            ViewBag.AllUser = albumTypeDA.getAllUserSimple();
            return View();
        }

        /// <summary>
        /// Load danh sách bản ghi dưới dạng bảng
        /// </summary>
        /// <returns></returns>
        public ActionResult ListItems()
        {
            ViewData.Model = _AlbumDA.getListSimpleByRequest(Request);
            ViewBag.PageHtml = _AlbumDA.GridHtmlPage;
            return View();
        }


        /// <summary>
        /// Trang xem chi tiết trong model
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxView()
        {
            var AlbumModel = _AlbumDA.getById(ArrID.FirstOrDefault());
            ViewData.Model = AlbumModel;
            return View();
        }

        /// <summary>
        /// Form dùng cho thêm mới, sửa. Load bằng Ajax dialog
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxForm()
        {
            var AlbumModel = new Base.Album()
            {
                AllowComment = true,
                Description = string.Empty,
                Details = string.Empty
            };

            if (DoAction == ActionType.Edit)
                AlbumModel = _AlbumDA.getById(ArrID.FirstOrDefault());


            ViewBag.AllCategory = new Data.Admin.AlbumTopicDA().getAllListSimple();
            ViewBag.Action = DoAction;
            ViewBag.ActionText = ActionText;
            return View(AlbumModel);
        }
        public ActionResult AjaxForms()
        {
            var AlbumModel = new Base.Album()
            {
                AllowComment = true,
                Description = string.Empty,
                Details = string.Empty
            };

            if (DoAction == ActionType.Edit)
                AlbumModel = _AlbumDA.getById(ArrID.FirstOrDefault());


            ViewBag.AllCategory = new Data.Admin.AlbumTopicDA().getAllListSimple();
            ViewBag.Action = DoAction;
            ViewBag.ActionText = ActionText;
            return View(AlbumModel);
        }
        
        public ActionResult AjaxApprove()
        {
            var contentDA = new Data.Admin.AlbumDA();
            ViewBag.AllStatus = contentDA.getAllStatusSimple();
            var Model = contentDA.getById(ArrID.FirstOrDefault());
            return View(Model);
        }


        /// <summary>
        /// Hứng các giá trị, phục vụ cho thêm, sửa, xóa, ẩn, hiện
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken()]
        public ActionResult Actions()
        {
            JsonMessage msg = new JsonMessage();
            Base.Album _Album = new Base.Album();
            List<Base.Album> lts_AlbumItems;
            StringBuilder stbMessage;


            List<int> IDValues;

            try
            {

                switch (DoAction)
                {

                    case ActionType.Add:
                        if (hasAdd)
                        {
                            UpdateModel(_Album);

                            _Album.Description = Sanitizer.GetSafeHtmlFragment(_Album.Description);
                            _Album.Details = Sanitizer.GetSafeHtmlFragment(_Album.Details);
                            _Album.CreateDate = DateTime.Now;
                            _Album.ModifyDate = DateTime.Now;
                            _Album.CreateBy = User.Identity.GetUserId();
                            _Album.ModifyBy = User.Identity.GetUserId();
                            _Album.StatusID = (int)Utils.WorkFlowStatus.BAN_NHAP;


                            #region cập nhật url
                            Base.Url url = new Base.Url();
                            url.UrlID = Request["Url"];
                            _Album.Urls.Add(url);
                            #endregion

                            _AlbumDA.Add(_Album);
                            _AlbumDA.Save();
                            msg = new JsonMessage()
                            {
                                Erros = false,
                                ID = _Album.ID.ToString(),
                                Message = string.Format("Đã thêm mới nội dung: <b>{0}</b>", Server.HtmlEncode(_Album.Title))
                            };
                        }
                        break;

                    case ActionType.Edit:
                        if (hasEdit)
                        {
                            _Album = _AlbumDA.getById(ArrID.FirstOrDefault());

                            UpdateModel(_Album);
                            _Album.Description = Sanitizer.GetSafeHtmlFragment(_Album.Description);
                            _Album.Details = Sanitizer.GetSafeHtmlFragment(_Album.Details);
                            _Album.ModifyDate = DateTime.Now;
                            _Album.ModifyBy = User.Identity.GetUserId();
                            _Album.StatusID = (int)Utils.WorkFlowStatus.CHO_DUYET;


                            _AlbumDA.Save();
                            msg = new JsonMessage()
                            {
                                Erros = false,
                                ID = _Album.ID.ToString(),
                                Message = string.Format("Đã cập nhật nội dung: <b>{0}</b>", Server.HtmlEncode(_Album.Title))
                            };
                        }
                        break;

                    case ActionType.Delete:
                        if (hasDelete)
                        {
                            lts_AlbumItems = _AlbumDA.getListByArrID(ArrID);
                            stbMessage = new StringBuilder();
                            foreach (var item in lts_AlbumItems)
                            {

                                _AlbumDA.Delete(item);
                                stbMessage.AppendFormat("Đã xóa nội dung <b>{0}</b>.<br />", Server.HtmlEncode(item.Title));
                            }
                            msg.ID = string.Join(",", ArrID);
                            _AlbumDA.Save();
                            msg.Message = stbMessage.ToString();
                        }
                        break;


                    case ActionType.Approve:
                        if (hasApprove)
                        {
                            _Album = _AlbumDA.getById(ArrID.FirstOrDefault());
                            Base.ApproveLog log = new Base.ApproveLog();
                            log.StatusID = Convert.ToInt32(Request["StatusID"]);
                            log.Description = Request["Description"];
                            log.CreatedDate = DateTime.Now;
                            log.UserID = User.Identity.GetUserId();
                            log.AlbumID = _Album.ID;

                            _Album.StatusID = log.StatusID;
                            _AlbumDA.QNewsDB.ApproveLogs.Add(log);

Source/QNews.Admin/Views/Album/AjaxApprove.cshtml
@model QNews.Base.Album
@{
    ViewBag.Title = "Kiểm duyệt album ảnh";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}
<script type="text/javascript">
    $(function () {


        $("#PublishDate").datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true
        });

        $("#ApproveForm").validate({
            rules: {
                StatusID:
                {
                    required: true
                },
                Description:
                {
                    maxlength: 1000
                }
            },
            submitHandler: function () { //onSubmit
                updateEditor();

                $.post(urlPostAction, $("#ApproveForm").mySerialize(), function (data) {
                    if (data.Erros)
                        createMessage("Đã có lỗi xảy ra", data.Message); // Tạo thông báo lỗi
                    else {
                        $("#dialog-form").dialog('close'); //Đóng form thêm mới - sửa
                        createCloseMessage("Thông báo", data.Message, '#Page=1&itemId=' + data.ID + '&message=' + data.Message + '&temp=' + Math.floor(Math.random() * 11) + ''); // Tạo thông báo khi click đóng thì chuyển đến url đích
                    }
                });
                return false;
            }
        });

        $("#close").click(function () {
            $("#dialog-form").html("").dialog('close');
        });
    });
</script>

<form id="ApproveForm">
    @Html.AntiForgeryToken()<input type="hidden" name="do" id="do" value="approve" />
    <input type="hidden" name="ItemID" id="ItemID" value="@Model.ID" />
    <fieldset class="forms">
        <legend>Kiểm duyệt album ảnh</legend>
        <table class="tableforms" cellspacing="1" width="100%">

            <tr>
                <td colspan="2"><strong>Kiểm duyệt nội dung: @Model.Title @Model.Description</strong></td>
            </tr>
            <tr>
                <td style="width:80px;"><label>Trạng thái</label></td>
                <td>
                    <ul>
                        @foreach (var item in ViewBag.AllStatus)
                        {
                            if (Model.StatusID == item.ID)
                            {
                                <li style="float:left; margin-right:15px;"><input type="radio" name="StatusID" value="@item.ID" disabled /><span style="color:#AAA;">@item.Name</span></li>
                            }
                            else
                            {
                                <li style="float:left; margin-right:15px;"><input type="radio" name="StatusID" value="@item.ID" /><span>@item.Name</span></li>
                            }

                        }
                    </ul>
                </td>
            </tr>

            <tr>
                <td><label>Ghi chú</label></td>
                <td>
                    <textarea rows="3" id="Description" name="Description" spellcheck="false" style="height:50px !important;"></textarea>
                </td>
            </tr>
            <tr>
                <td>File đính kèm</td>
                <td>
                    <ul>
                       
                    </ul>
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>


            <tr>
                <td class="submit" colspan="2">
                    <button id="submit" type="submit" class="primaryAction">Thực hiện</button>
                    <button id="reset" type="reset" class="primaryAction">Nhập lại</button>
                    <button id="close" type="button" class="primaryAction">Đóng lại</button>
                </td>
            </tr>
        </table>
    </fieldset>

    <fieldset class="forms">
        <legend>Lịch sử kiểm duyệt album ảnh</legend>

        <table class="tableforms" cellspacing="1" width="100%">
            <tr>
                <th>Người thực hiện</th>
                <th>Thời gian thực hiện</th>
                <th>Trạng thái</th>
                <th>Ghi chú</th>
            </tr>
            @foreach (var item in Model.ApproveLogs)
            {
                <tr>
                    <td>@item.AspNetUser.UserName</td>
                    <td>@item.CreatedDate.ToString("dd/MM/yyyy hh:mm:ss tt")</td>
                    <td>@item.Status.Name</td>
                    <td>@item.Description</td>
                </tr>
            }
        </table>

    </fieldset>
</form>

Source/QNews.Admin/Views/Album/AjaxForm.cshtml
@model QNews.Base.Album
@{
    ViewBag.Title = ViewBag.ActionText + " album ảnh";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}
<script type="text/javascript">
    $(function () {

        var addUrl = @((ViewBag.Action == QNews.Admin.Controllers.ActionType.Add).ToString().ToLower());

        if(addUrl)
        {
            $("#AlbumForm #Title").keyup(function(){
                $("#AlbumForm #Url").val(UnicodeToAscii($(this).val()));
            });

            $("#AlbumForm #Title, #AlbumForm #Url").blur(function(){ //Sau khi thoát kiểm tra url
                $.post("/Album/CheckUrl", { "url" : ""+$("#AlbumForm #Url").val()+""}, function(data){
                    if(data){
                        createMessage('Đã có lỗi xảy ra.', 'Url <strong>'+$("#AlbumForm #Url").val()+'</strong> đã tồn tại trong hệ thống. Vui lòng nhập url khác.');
                        //$("#AlbumForm #Url").focus();
                    }
                });
            });
        }

        createCKFider('Image', 120);
        LoadCKEDITOR('Details', true);
        $.datepicker.setDefaults($.datepicker.regional['vi']);

        
        $('#PublishDate').datetimepicker({
            controlType: 'select',
            oneLine: true,
            timeFormat: 'HH:mm:ss',
            dateFormat: 'dd/mm/yy'
        })


        $("#AlbumForm").validate({
            rules: {
                PublishDate:
                {
                    //date: true
                },
                Title:
                {
                    required: true,
                    minlength: 2,
                    maxlength: 255
                },
                Url:
                {
                    required: true,
                    minlength: 2,
                    maxlength: 255
                },
                Description:
                {
                    minlength: 15,
                    maxlength: 1000
                }
            },
            submitHandler: function () { //onSubmit
                updateEditor();

                $.post(urlPostAction, $("#AlbumForm").mySerialize(), function (data) {
                    if (data.Erros)
                        createMessage("Đã có lỗi xảy ra", data.Message); // Tạo thông báo lỗi
                    else {
                        $("#dialog-form").dialog('close'); //Đóng form thêm mới - sửa
                        createCloseMessage("Thông báo", data.Message, '#Page=1&itemId=' + data.ID + '&message=' + data.Message + '&temp=' + Math.floor(Math.random() * 11) + ''); // Tạo thông báo khi click đóng thì chuyển đến url đích
                    }
                });
                return false;
            }
        });

        $("#close").click(function () {
            $("#dialog-form").html("").dialog('close');
        });

        $("select.fullwidthForm").select2({ width: '100%' });
    });
</script>

<form id="AlbumForm">
    @Html.AntiForgeryToken()<input type="hidden" name="do" id="do" value="@ViewBag.Action" />
    <input type="hidden" name="ItemID" id="ItemID" value="@Model.ID" />
    <input type="hidden" id="listValueFileAttach" name="listValueFileAttach" />
    <input type="hidden" id="listValueFileAttachRemove" name="listValueFileAttachRemove" />
    <input type="hidden" name="TagValues" id="TagValues" />
    <fieldset class="forms">
        <legend>Thông tin về album ảnh</legend>
        <table class="tableforms" cellspacing="1" width="100%">
            <tr>
                <td style="width:160px;"><label>Tên album ảnh</label></td>
                <td>
                    <input type="text" name="Title" id="Title" value="@Model.Title" />
                </td>
            </tr>
            <tr>
                <td class="label"><label>Url album ảnh</label></td>
                <td>
                    @if (@ViewBag.Action == QNews.Admin.Controllers.ActionType.Add)
                    {
                        <input type="text" name="Url" id="Url" />
                    }
                    else
                    {
                        <input type="text" disabled name="Url" id="Url" value="@Model.Urls.Select(o => o.UrlID).FirstOrDefault()" />
                    }
                </td>

            </tr>

            <tr>
                <td><label>Mô tả</label></td>
                <td>
                    <textarea rows="5" id="Description" name="Description" spellcheck="false">@Model.Description</textarea>
                </td>
            </tr>

            <tr>
                <td><label>Hình ảnh đại diện</label></td>
                <td>
                    <button id="ImageButton" type="button" class="primaryAction">Chọn hỉnh ảnh đại diện</button>
                    <br />
                    <i>Hoặc nhập đường link ảnh từ liên kết bên ngoài</i>
                    <br />
                    <input type="text" value="@((!string.IsNullOrEmpty(Model.Image) && Model.Image.Contains("http")) ? Model.Image : string.Empty)" name="OtherImage" id="OtherImage" />

                    <div id="ImageValues">
                        <input type="hidden" name="Image" value="@Model.Image" />
                        <img src="@(string.IsNullOrEmpty(Model.Image) ? "/Content/Admin/images/no_image.gif" : Model.Image)" style="border:1px solid #ccc; width:120px; margin-top:2px; float:left;" />
                        <button id="ImageButtonDelete" onclick="clearFKFider('Image', 120);" type="button" class="primaryAction" style="margin:25px 10px;">Xóa ảnh</button>
                    </div>
                </td>
            </tr>

            <tr>
                <td><label>Ngày xuất bản</label></td>
                <td>
                    <input type="text" name="PublishDate" id="PublishDate" value="@((Model.PublishDate.HasValue) ? Model.PublishDate.Value.ToString("dd/MM/yyyy") : "")" />
                </td>
            </tr>

            <tr>
                <td><label>Chủ đề</label></td>
                <td>
                    
                    <select name="TopicID" id="TopicID" class="fullwidthForm">
                        <option value=""></option>
                        @foreach (var item in ViewBag.AllCategory)
                        {
                            <option value="@item.ID" @(Model.TopicID == item.ID ? " selected" : "")>@item.Title</option>
                        }
                    </select>

                </td>
            </tr>


            <tr>
                <td><label>Nội dung chi tiết</label></td>
                <td>
                    <textarea rows="5" id="Details" name="Details" spellcheck="false">@Model.Details</textarea>
                </td>
            </tr>


            <tr>
                <td><label>Là album nổi bật</label></td>
                <td>
                    <input type="checkbox" name="IsHot" id="IsHot" value="True" @((Model.IsHot) ? " checked" : string.Empty) />
                </td>
            </tr>

            <tr>
                <td><label>Cho phép gửi bình luận</label></td>
                <td>
                    <input type="checkbox" name="AllowComment" id="AllowComment" value="True" @((Model.AllowComment) ? " checked" : string.Empty) />
                </td>
            </tr>


            <tr>
                <td><label>Lượt xem</label></td>
                <td>
                    <input type="text" value="@Model.Viewed" name="Viewed" id="Viewed" />
                </td>
            </tr>

            <tr>
                <td><label>Nguồn nội dung</label></td>
                <td>
                    <input type="text" value="@Model.Source" name="Source" id="Source" />
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>
            <tr>
                <td class="submit" colspan="2">
                    <button id="submit" type="submit" class="primaryAction">@ViewBag.ActionText</button>
                    <button id="reset" type="reset" class="primaryAction">Nhập lại</button>
                    <button id="close" type="button" class="primaryAction">Đóng lại</button>
                </td>
            </tr>
        </table>
    </fieldset>
</form>

Source/QNews.Admin/Views/Album/AjaxForms.cshtml
@model QNews.Base.Album
@{
    ViewBag.Title = ViewBag.ActionText + " album ảnh";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}
<div class="jumbotron">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
           
        </div>
        <button type="submit">Upload File</button>
    }
</div>

Source/QNews.Admin/Views/Album/Index.cshtml
@{
    ViewBag.Title = "Quản lý album ảnh";
    bool hasAdd = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Add");
    bool hasEdit = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Edit");
    bool hasDelete = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Delete");
    bool hasApprove = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Approve");
}
<script type="text/javascript">

    urlLists = '@Url.Action("ListItems", "Album")';
    urlForm = '@Url.Action("AjaxForm", "Album")';
    urlFormApprove = '@Url.Action("AjaxApprove", "Album")';
    urlPostAction = '@Url.Action("Actions", "Album")';
    urlView = '@Url.Action("AjaxView", "Album")';
    formWidth = 1100;
    formHeight = 650;
    viewWidth = 1100;
    viewHeight = 650;

    $(document).ready(function () {
        initAjaxLoad(urlLists, "#JobGriditems");

        $("#gridSearch").submit(function () {
            var form = $("#gridSearch");
            window.location.href = '#' + getValueFormMutilSelect(form);
            return false;
        });

        $("#btn_add").click(function () {
            $("#dialog-form").dialog(
				{
				    title: "Thêm mới album ảnh",
				    width: formWidth,
				    height: formHeight
				}
			).load(encodeURI(urlForm + "?do=Add")).dialog("open");
            return false;
        });

        $.datepicker.setDefaults($.datepicker.regional['vi']);
        $("#TuNgay").datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            onSelect: function (dateStr) {
                var min = $(this).datepicker('getDate') || new Date(); // Selected date or today if none
                $('#DenNgay').datepicker('option', { minDate: min });
            }
        });

        $("#DenNgay").datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            minDate: $("#TuNgay").val()
        });

        $("select.fullwidth").select2({ width: 605 });
    });

    function getVersion(versionId) {
        var tokenValid = $("input[name='__RequestVerificationToken']").val();
        $.post(urlPostAction, { "do": "reset", "ItemID": versionId, "__RequestVerificationToken": "" + tokenValid + "" }, function (data) {
            if (data.Erros)
                createMessage("Đã có lỗi xảy ra", data.Message); // Tạo thông báo lỗi
            else {
                $("#dialog-form").dialog('close'); //Đóng form thêm mới - sửa
                createCloseMessage("Thông báo", data.Message, '#Page=1&itemId=' + data.ID + '&message=' + data.Message + '&temp=' + Math.floor(Math.random() * 11) + ''); // Tạo thông báo khi click đóng thì chuyển đến url đích
            }
        });
    }

</script>
<div class="zone zone-content">
    <h1>Quản lý album ảnh</h1>

    <div class="headear">
        <div style="width: 700px; padding: 10px;" class="searchbox advance leftright">
            <form id="gridSearch">
                <fieldset class="bulk-actions">
                    <div class="row">
                        <div class="left">
                            <label for="Keyword">Từ khóa:</label>
                            <input type="text" name="Keyword" id="Keyword" value="Từ khóa tìm kiếm" onfocus="if(this.value=='Từ khóa tìm kiếm') this.value='';" onblur="if(this.value=='') this.value='Từ khóa tìm kiếm';" />
                        </div>
                        <div class="right">
                            <label for="SearchIn">Tìm trong:</label>
                            <select name="SearchIn" id="SearchIn" class="mutil" multiple="multiple">
                                <option value="Title" selected>Tên album ảnh</option>
                                <option value="Description">Mô tả</option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="left">
                            <label>Xuất bản:</label>
                            <span><i>Từ</i></span>
                            <input type="text" name="TuNgay" id="TuNgay" style="width:92px" />
                            <span><i>Đến</i></span>
                            <input type="text" name="DenNgay" id="DenNgay" style="width:91px" />
                        </div>

                        <div class="right">
                            <label>Trạng thái:</label>
                            <select name="StatusID">
                                <option value="">Tất cả</option>
                                @foreach (var item in ViewBag.AllStatus)
                                {
                                    <option value="@item.ID">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="left">
                            <label>Người tạo:</label>
                            <select name="CreateBy">
                                <option value="">Tất cả</option>
                                @foreach (var item in ViewBag.AllUser)
                                {
                                    <option value="@item.ID">@item.UserName</option>
                                }
                            </select>
                        </div>

                        <div class="right">
                            <label>Sửa cuối:</label>
                            <select name="ModifyBy">
                                <option value="">Tất cả</option>
                                @foreach (var item in ViewBag.AllUser)
                                {
                                    <option value="@item.ID">@item.UserName</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <label>Chủ đề</label>
                        <select name="TopicID" class="fullwidth">
                            <option value="">Tất cả</option>
                            @foreach (var item in ViewBag.AllCategory)
                            {
                                <option value="@item.ID">@item.Title</option>
                            }
                        </select>
                    </div>
                    <div class="row">
                        <div class="submit">
                            <button name="submit.Search" type="submit">Tìm kiếm</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>

        <div class="manage">
            @if (hasAdd)
            {
                @Html.ActionLink("Thêm mới", "Create", new { }, new { @class = "add button primaryAction", @id = "btn_add" })
            }
        </div>
    </div>

    <div id="JobGriditems">

    </div>
</div>