Source/QNews.Admin/Controllers/CloneNodeRemoveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QNews.Data;
using QNews.Utils;
using QNews.Base;
using System.Text;
using QNews.Models;

namespace QNews.Admin.Controllers
{
    /// <summary>
    /// Class sử dụng cho quản lý dữ liệu xóa bỏ
    /// </summary>
    public class CloneNodeRemoveController : BaseController
    {
        Clone_RemoveDA noderemoveDA = new Clone_RemoveDA("#");

        public ActionResult AutoComplete()
        {
            if (DoAction == ActionType.Add) //Nếu thêm từ khóa
            {

                List<JsonMessage> LtsMsg = new List<JsonMessage>();
                JsonMessage msg;
                string noderemoveValue = Request["Values"];
                if (string.IsNullOrEmpty(noderemoveValue))
                {
                    msg = new JsonMessage()
                    {
                        Erros = true,
                        Message = "Bạn phải nhập Xóa theo tên miền"
                    };
                    LtsMsg.Add(msg);
                }
                else
                {
                    var noderemoves = noderemoveDA.getByNameArray(noderemoveValue);
                    if (noderemoves == null || noderemoves.Count == 0)
                    {
                        msg = new JsonMessage()
                        {
                            Erros = true,
                            Message = "Tên miền không tồn tại trong hệ thống"
                        };
                        LtsMsg.Add(msg);
                    }
                    else
                    {
                        foreach (var noderemove in noderemoves)
                        {
                            msg = new JsonMessage()
                            {
                                Erros = false,
                                ID = noderemove.ID.ToString(),
                                Message = noderemove.Title
                            };
                            LtsMsg.Add(msg);
                        }
                    }
                }
                return Json(LtsMsg, JsonRequestBehavior.AllowGet);
            }
            else //Nếu xem
            {
                string query = Request["query"];
                var ltsResults = noderemoveDA.GetListSimpleByAutoComplete(query, 10);
                AutoCompleteItem ResulValues = new AutoCompleteItem()
                {
                    query = query,
                    data = ltsResults.Select(o => o.ID.ToString()).ToList(),
                    suggestions = ltsResults.Select(o => o.Title).ToList()
                };
                return Json(ResulValues, JsonRequestBehavior.AllowGet);
            }
        }


        /// <summary>
        /// Trang chủ, index. Load ra grid dưới dạng ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Load danh sách bản ghi dưới dạng bảng
        /// </summary>
        /// <returns></returns>
        public ActionResult ListItems()
        {
            ViewData.Model = noderemoveDA.getListSimpleByRequest(Request);
            ViewBag.PageHtml = noderemoveDA.GridHtmlPage;
            return View();
        }


        /// <summary>
        /// Trang xem chi tiết trong model
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxView()
        {
            var BankModel = noderemoveDA.getById(ArrID.FirstOrDefault());
            ViewData.Model = BankModel;
            return View();
        }

        /// <summary>
        /// Form dùng cho thêm mới, sửa. Load bằng Ajax dialog
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxForm()
        {
            var BankModel = new Base.Clone_Remove();
            if (DoAction == ActionType.Edit)
                BankModel = noderemoveDA.getById(ArrID.FirstOrDefault());

            ViewBag.AllDomain = new Data.Clone_DomainDA().getListSimpleAll();
            ViewBag.AllType = noderemoveDA.QNewsDB.Clone_Type.ToList(); 
            ViewData.Model = BankModel;
            ViewBag.Action = DoAction;
            ViewBag.ActionText = ActionText;
            return View();
        }


        /// <summary>
        /// Hứng các giá trị, phục vụ cho thêm, sửa, xóa, ẩn, hiện
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken()]public ActionResult Actions()
        {
            JsonMessage msg = new JsonMessage();
            Clone_Remove noderemove = new Clone_Remove();
            List<Clone_Remove> ltsBankItems;
            StringBuilder stbMessage;

            switch (DoAction)
            {
                case ActionType.Add:
                    if (hasAdd)
                    {
                        UpdateModel(noderemove);
                        noderemoveDA.Add(noderemove);
                        noderemoveDA.Save();
                        msg = new JsonMessage()
                        {
                            Erros = false,
                            ID = noderemove.ID.ToString(),
                            Message = string.Format("Đã thêm mới dữ liệu xóa bỏ: <b>{0}</b>", Server.HtmlEncode(noderemove.Title))
                        };
                    }
                    break;

                case ActionType.Edit:
                    if (hasEdit)
                    {
                        noderemove = noderemoveDA.getById(ArrID.FirstOrDefault());
                        UpdateModel(noderemove);
                        noderemoveDA.Save();
                        msg = new JsonMessage()
                        {
                            Erros = false,
                            ID = noderemove.ID.ToString(),
                            Message = string.Format("Đã cập nhật dữ liệu xóa bỏ: <b>{0}</b>", Server.HtmlEncode(noderemove.Title))
                        };
                    }
                    break;

                case ActionType.Delete:
                    if (hasDelete)
                    {
                        ltsBankItems = noderemoveDA.getListByArrID(ArrID);
                        stbMessage = new StringBuilder();
                        try
                        {
                            foreach (var item in ltsBankItems)
                            {
                                noderemoveDA.Delete(item);
                                stbMessage.AppendFormat("Đã xóa dữ liệu xóa bỏ <b>{0}</b>.<br />", Server.HtmlEncode(item.Title));
                            }
                            msg.ID = string.Join(",", ArrID);
                            noderemoveDA.Save();
                        }
                        catch (Exception ex)
                        {
                            stbMessage.Append(ex.Message);
                        }
                        msg.Message = stbMessage.ToString();
                    }
                    break;
            }

            if (string.IsNullOrEmpty(msg.Message))
            {
                msg.Message = "Không có hành động nào được thực hiện.";
                msg.Erros = true;
            }

            return Json(msg, JsonRequestBehavior.AllowGet);
        }
    }
}

Source/QNews.Admin/Views/CloneNodeRemove/AjaxForm.cshtml
@model QNews.Base.Clone_Remove
@{
    ViewBag.Title = ViewBag.ActionText + " dữ liệu xóa bỏ";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {

        $("#CloneNodeRemoveForm").validate({
            rules: {
                Title:
                {
                    required: true,
                    minlength: 2,
                    maxlength: 255
                },
                DomainID:
                {
                    required: true
                },
                XpathRemoveIn:
                {
                    required: true
                },
                XpathValue:
                {
                    required: true,
                    minlength: 2,
                    maxlength: 255
                }
            },
            submitHandler: function () { //onSubmit
                $.post(urlPostAction, $("#CloneNodeRemoveForm").serialize({ checkboxesAsBools: true }), function (data) {
                    if (data.Erros)
                        createMessage("Đã có lỗi xảy ra", data.Message); // Tạo thông báo lỗi
                    else {
                        $("#dialog-form").dialog('close'); //Đóng form thêm mới - sửa
                        createCloseMessage("Thông báo", data.Message, '#Page=1&itemId=' + data.ID + '&message=' + data.Message + '&temp=' + Math.floor(Math.random() * 11) + ''); // Tạo thông báo khi click đóng thì chuyển đến url đích
                    }
                });
                return false;
            }
        });

        $("#close").click(function () {
            $("#dialog-form").html("").dialog('close');
        });
    });
</script>


<form id="CloneNodeRemoveForm">
    @Html.AntiForgeryToken()<input type="hidden" name="do" id="do" value="@ViewBag.Action" />
    <input type="hidden" name="ItemID" id="ItemID" value="@Model.ID" />
    <fieldset class="forms">
        <table class="tableforms" cellspacing="1" width="100%">
            <tr>
                <td style="width:120px;"><label>Tên node xóa bỏ</label></td>
                <td>
                    <input type="text" name="Title" id="Title" value="@Model.Title" />
                </td>
            </tr>

            <tr>
                <td><label>Xóa theo tên miền</label></td>
                <td>
                    <select name="DomainID" id="DomainID">
                        <option value="">...</option>
                        @foreach (var item in ViewBag.AllDomain)
                        {
                            <option value="@item.ID" @((item.ID == Model.DomainID) ? " selected" : "")>@item.Title</option>
                        }
                    </select>
                </td>
            </tr>

            <tr>
                <td><label>Xóa theo trong vùng</label></td>
                <td>
                    <select name="XpathRemoveIn" id="XpathRemoveIn">
                        <option value="">...</option>
                        @foreach (var item in ViewBag.AllType)
                        {
                            <option value="@item.ID" @((item.ID == Model.XpathRemoveIn) ? " selected" : "")>@item.Title</option>
                        }
                    </select>
                </td>
            </tr>

            <tr>
                <td><label>Mã Xpath</label></td>
                <td>
                    <input type="text" name="XpathValue" id="XpathValue" value="@Model.XpathValue" />
                </td>
            </tr>

            <tr>
                <td></td>
                <td>
                    <button id="submit" type="submit" class="primaryAction">@ViewBag.ActionText</button>
                    <button id="reset" type="reset" class="primaryAction">Nhập lại</button>
                    <button id="close" type="button" class="primaryAction">Đóng lại</button>
                </td>
            </tr>
        </table>
    </fieldset>
</form>

Source/QNews.Admin/Views/CloneNodeRemove/AjaxView.cshtml
@model QNews.Base.Clone_Remove

@{
    ViewBag.Title = "Xem chi tiết";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}

<fieldset class="forms">
    <table class="tableforms tabledetails" cellspacing="1" width="100%">
        <tr>
            <td style="width:90px;" class="label"><label>Tên node xóa bỏ</label></td>
            <td>
                @Html.DisplayFor(model => model.Title)
            </td>
        </tr>

        <tr>
            <td style="width:90px;" class="label"><label>Xóa theo tên miền</label></td>
            <td>
                @Html.DisplayFor(model => model.Clone_Domain.Title)
            </td>
        </tr>
        <tr>
            <td class="label"><label>Xóa trong</label></td>
            <td>
                @Model.Clone_Type.Title
            </td>
        </tr>

        <tr>
            <td class="label"><label>Xpath xóa bỏ</label></td>
            <td>@Model.XpathValue</td>
        </tr>
        

    </table>
</fieldset>

Source/QNews.Admin/Views/CloneNodeRemove/Index.cshtml
@{
    ViewBag.Title = "Quản lý dữ liệu xóa bỏ";
    Layout = "~/Views/Shared/_Layout.cshtml";
    bool hasAdd = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Add");
    bool hasEdit = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Edit");
    bool hasDelete = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Delete");
    bool hasApprove = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Approve");
}
<script type="text/javascript">

    urlLists = '@Url.Action("ListItems", "CloneNodeRemove")';
    urlForm = '@Url.Action("AjaxForm", "CloneNodeRemove")';
    urlPostAction = '@Url.Action("Actions", "CloneNodeRemove")';
    urlView = '@Url.Action("AjaxView", "CloneNodeRemove")';
    formWidth = 800;
    formHeight = 'auto';
    viewWidth = 800;
    viewHeight = 'auto';

    $(document).ready(function () {
        initAjaxLoad(urlLists, "#noderemoveGriditems");

        $("#gridSearch").submit(function () {
            var form = $("#gridSearch");
            window.location.href = '#' + getValueFormMutilSelect(form);
            return false;
        });

        $("#btn_add").click(function () {
            $("#dialog-form").dialog(
				{
				    title: "Thêm mới dữ liệu xóa bỏ",
				    width: formWidth,
				    height: formHeight
				}
			).load(encodeURI(urlForm + "?do=Add")).dialog("open");
            return false;
        });
    });
</script>

<div class="zone zone-content">
    <h1>Quản lý dữ liệu xóa bỏ</h1>
    <div class="headear">
        <div class="searchbox">
            <form id="gridSearch">
            <fieldset class="bulk-actions">
                <label for="Keyword">Tên miền:</label>
                <input type="text" name="Keyword" id="Keyword" value="Từ khóa tìm kiếm" onfocus="if (this.value == 'Từ khóa tìm kiếm') this.value = '';" onblur="    if (this.value == '') this.value = 'Từ khóa tìm kiếm';" />
                <label for="SearchIn">Tìm trong:</label>
                <select name="SearchIn" id="SearchIn" class="mutil">
                    <option value="DomainName">Xóa theo tên miền</option>
                    <option value="XpathValue">Xpath xóa bỏ</option> 
                </select>
                <button name="submit.Search" type="submit"">Tìm kiếm</button>
            </fieldset>
            </form>
        </div>
        
        <div class="manage">
            @if (hasAdd) { 
                @Html.ActionLink("Thêm mới dữ liệu xóa bỏ", "Create", new {}, new { @class = "add button primaryAction", @id= "btn_add"})
            }
        </div>
    </div>
    <div id="noderemoveGriditems">
    
    </div>
</div>

Source/QNews.Admin/Views/CloneNodeRemove/ListItems.cshtml
@model IEnumerable<QNews.Models.NodeRemoveItem>
@{
    ViewBag.Title = "ListBank";
    Layout = "~/Views/Shared/_Ajax.cshtml";
    bool hasAdd = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Add");
    bool hasEdit = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Edit");
    bool hasDelete = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Delete");
    bool hasApprove = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Approve");
}
@Html.AntiForgeryToken()
<script type="text/javascript">
    $(document).ready(function () {
        registerGridView('#gridItems');
    });
</script>
<div class="grid-container" id="gridItems">
    <table class="gridView" cellspacing="1">
        <tr>
            <th><a href="#Field=ID">ID<span /></a></th>
            <th><a href="#Field=Title">Tên node xóa bỏ<span /></a></th>
            <th><a href="#Field=DomainName">Xóa theo tên miền<span /></a></th>
            <th><a href="#Field=RemoveIn">Vùng sẽ xóa<span /></a></th>
            <th><a href="#Field=XpathValue">Xpath xóa bỏ<span /></a></th>
            <th class="act_view"></th>
            @if (hasEdit)
            {
                <th class="act_edit"></th>
            }
            @if (hasDelete)
            {
                <th class="act_delete">
                    <a href="#deleteAll" class="deleteAll" title="Xóa danh sách đã chọn">
                        <img src="/Content/Admin/images/gridview/delete.gif" style="border: none" alt="Xóa danh sách đã chọn" />
                    </a>
                </th>
                <th class="act_roles">
                    <input value="" type="checkbox" class="checkAll" />
                </th>
            }
        </tr>
        @foreach (var item in Model)
        {
            <tr title="@item.Title">
                <td>@item.ID</td>
                <td>@item.Title</td>
                <td>@item.DomainName</td>
                <td>@item.RemoveIn</td>
                <td>@item.XpathValue</td>
                <td class="act_view">@Grid.ActionView(item.ID, item.Title)</td>
                @if (hasEdit)
                {
                    <td class="act_edit">
                        @Grid.ActionEdit(item.ID, item.Title)
                    </td>
                }
                @if (hasDelete)
                {
                    <td class="act_delete">@Grid.ActionDelete(item.ID, item.Title)</td>
                    <td class="act_roles"><input type="checkbox" value="@item.ID" class="check" /></td>
                }
            </tr>
        }
    </table>
    @Html.Raw(ViewBag.PageHtml)
</div>