Source/QNews.Admin/Controllers/AlbumPictureController.cs
using QNews.Data.Admin;
using QNews.Models;
using QNews.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Security.Application;

namespace QNews.Admin.Controllers
{
    public class AlbumPictureController : BaseController
    {
        AlbumPictureDA _AlbumPictureDA = new AlbumPictureDA("#");
        
        public ActionResult Details(int id)
        {
            AlbumPictureDA albumPictureDA = new AlbumPictureDA();
            var model = albumPictureDA.getById(id);
            ViewBag.AllStatus = albumPictureDA.getAllStatusSimple();
            ViewBag.AllUser = albumPictureDA.getAllUserSimple();
            return View(model);
        }

        public ActionResult Addnew()
        {
           
            return View();
        }


        public ActionResult AutoComplete()
        {
            if (DoAction == ActionType.Add) //Nếu thêm mới
            {
                JsonMessage msg = new JsonMessage();
                string SearchValue = Request["Values"];
                if (string.IsNullOrEmpty(SearchValue))
                {
                    msg = new JsonMessage()
                    {
                        Erros = true,
                        Message = "Bạn phải nhập tên nội dung"
                    };
                }
                else
                {
                    var _AlbumPicture = _AlbumPictureDA.getByName(SearchValue);
                    if (_AlbumPicture == null)
                    {
                        msg = new JsonMessage()
                        {
                            Erros = true,
                            Message = "nội dung không tồn tại trong hệ thống"
                        };
                    }
                    else
                    {
                        msg = new JsonMessage()
                        {
                            Erros = false,
                            ID = _AlbumPicture.ID.ToString(),
                            Message = _AlbumPicture.Title
                        };
                    }
                }
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            else //Nếu xem từ khóa
            {
                string query = Request["query"];
                var ltsResults = _AlbumPictureDA.GetListSimpleByAutoComplete(query, 10);
                AutoCompleteItem ResulValues = new AutoCompleteItem()
                {
                    query = query,
                    data = ltsResults.Select(o => o.ID.ToString()).ToList(),
                    suggestions = ltsResults.Select(o => o.Title).ToList()
                };
                return Json(ResulValues, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Trang chủ, index. Load ra grid dưới dạng ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            AlbumDA albumDA = new AlbumDA();
            ViewBag.AllCategory = albumDA.getAllListSimple();
            ViewBag.AllStatus = albumDA.getAllStatusSimple();
            ViewBag.AllUser = albumDA.getAllUserSimple();
            return View();
        }

        /// <summary>
        /// Load danh sách bản ghi dưới dạng bảng
        /// </summary>
        /// <returns></returns>
        public ActionResult ListItems()
        {
            ViewData.Model = _AlbumPictureDA.getListSimpleByRequest(Request);
            ViewBag.PageHtml = _AlbumPictureDA.GridHtmlPage;
            return View();
        }


        /// <summary>
        /// Trang xem chi tiết trong model
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxView()
        {
            var AlbumPictureModel = _AlbumPictureDA.getById(ArrID.FirstOrDefault());
            ViewData.Model = AlbumPictureModel;
            return View();
        }

        /// <summary>
        /// Form dùng cho thêm mới, sửa. Load bằng Ajax dialog
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxForm()
        {
            var AlbumPictureModel = new Base.AlbumPicture()
            {
                AllowComment = true,
                Description = string.Empty
            };

            if (DoAction == ActionType.Edit)
                AlbumPictureModel = _AlbumPictureDA.getById(ArrID.FirstOrDefault());


            ViewBag.AllCategory = new Data.Admin.AlbumDA().getAllListSimple();
            ViewBag.Action = DoAction;
            ViewBag.ActionText = ActionText;
            return View(AlbumPictureModel);
        }

        public ActionResult AjaxApprove()
        {
            var contentDA = new Data.Admin.AlbumPictureDA();
            ViewBag.AllStatus = contentDA.getAllStatusSimple();
            var Model = contentDA.getById(ArrID.FirstOrDefault());
            return View(Model);
        }


        /// <summary>
        /// Hứng các giá trị, phục vụ cho thêm, sửa, xóa, ẩn, hiện
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken()]public ActionResult Actions()
        {
            JsonMessage msg = new JsonMessage();
            Base.AlbumPicture _AlbumPicture = new Base.AlbumPicture();
            List<Base.AlbumPicture> lts_AlbumPictureItems;
            StringBuilder stbMessage;


            List<int> IDValues;

            try { 
            switch (DoAction)
            {

                case ActionType.Add:
                    if (hasAdd)
                    {
                        UpdateModel(_AlbumPicture);
                        _AlbumPicture.Description = Sanitizer.GetSafeHtmlFragment(_AlbumPicture.Description);
                        _AlbumPicture.CreateDate = DateTime.Now;
                        _AlbumPicture.ModifyDate = DateTime.Now;
                        _AlbumPicture.CreateBy = User.Identity.GetUserId();
                        _AlbumPicture.ModifyBy = User.Identity.GetUserId();
                        _AlbumPicture.StatusID = (int)Utils.WorkFlowStatus.BAN_NHAP;

                        _AlbumPictureDA.Add(_AlbumPicture);
                        _AlbumPictureDA.Save();
                        msg = new JsonMessage()
                        {
                            Erros = false,
                            ID = _AlbumPicture.ID.ToString(),
                            Message = string.Format("Đã thêm mới nội dung: <b>{0}</b>", Server.HtmlEncode(_AlbumPicture.Title))
                        };
                    }
                    break;

                case ActionType.Edit:
                    if (hasEdit)
                    {
                        _AlbumPicture = _AlbumPictureDA.getById(ArrID.FirstOrDefault());

                        UpdateModel(_AlbumPicture);
                        _AlbumPicture.Description = Sanitizer.GetSafeHtmlFragment(_AlbumPicture.Description);
                        _AlbumPicture.ModifyDate = DateTime.Now;
                        _AlbumPicture.ModifyBy = User.Identity.GetUserId();
                        _AlbumPicture.StatusID = (int)Utils.WorkFlowStatus.CHO_DUYET;


                        _AlbumPictureDA.Save();
                        msg = new JsonMessage()
                        {
                            Erros = false,
                            ID = _AlbumPicture.ID.ToString(),
                            Message = string.Format("Đã cập nhật nội dung: <b>{0}</b>", Server.HtmlEncode(_AlbumPicture.Title))
                        };
                    }
                    break;

                case ActionType.Delete:
                    if (hasDelete)
                    {
                        lts_AlbumPictureItems = _AlbumPictureDA.getListByArrID(ArrID);
                        stbMessage = new StringBuilder();
                        foreach (var item in lts_AlbumPictureItems)
                        {

                            _AlbumPictureDA.Delete(item);
                            stbMessage.AppendFormat("Đã xóa nội dung <b>{0}</b>.<br />", Server.HtmlEncode(item.Title));
                        }
                        msg.ID = string.Join(",", ArrID);
                        _AlbumPictureDA.Save();
                        msg.Message = stbMessage.ToString();
                    }
                    break;


                case ActionType.Approve:
                    if (hasApprove)
                    {
                        _AlbumPicture = _AlbumPictureDA.getById(ArrID.FirstOrDefault());
                        Base.ApproveLog log = new Base.ApproveLog();
                        log.StatusID = Convert.ToInt32(Request["StatusID"]);
                        log.Description = Request["Description"];
                        log.CreatedDate = DateTime.Now;
                        log.UserID = User.Identity.GetUserId();
                        log.PictureID = _AlbumPicture.ID;

                        _AlbumPicture.StatusID = log.StatusID;
                        _AlbumPictureDA.QNewsDB.ApproveLogs.Add(log);
                        _AlbumPictureDA.Save();

                        var status = _AlbumPictureDA.QNewsDB.Status.Where(o => o.ID == log.StatusID).FirstOrDefault().Name;

                        msg = new JsonMessage()
                        {
                            Erros = false,
                            ID = _AlbumPicture.ID.ToString(),
                            Message = string.Format("Đã thực hiện <strong>{1}</strong> nội dung <b>{0}</b>", _AlbumPicture.Title, status)
                        };
                    }
                    break;
            }

            if (string.IsNullOrEmpty(msg.Message))
            {
                msg.Message = "Không có hành động nào được thực hiện.";
                msg.Erros = true;
            }
            }
            catch (Exception e)
            {

Source/QNews.Admin/Views/AlbumPicture/Addnew.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Addnew form</title>
</head>
<body>
    <form class="box" method="post" action="" enctype="multipart/form-data">
        <div class="box__input">
            <input class="box__file" type="file" name="files[]" id="file" data-multiple-caption="{count} files selected" multiple />
            <label for="file"><strong>Choose a file</strong><span class="box__dragndrop"> or drag it here</span>.</label>
            <button class="box__button" type="submit">Upload</button>
        </div>
        <div class="box__uploading">Uploading&hellip;</div>
        <div class="box__success">Done!</div>
        <div class="box__error">Error! <span></span>.</div>
    </form>
</body>
</html>

Source/QNews.Admin/Views/AlbumPicture/AjaxApprove.cshtml
@model QNews.Base.AlbumPicture
@{
    ViewBag.Title = "Kiểm duyệt albumPicture ảnh";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}
<script type="text/javascript">
    $(function () {


        $("#PublishDate").datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true
        });

        $("#ApproveForm").validate({
            rules: {
                StatusID:
                {
                    required: true
                },
                Description:
                {
                    maxlength: 1000
                }
            },
            submitHandler: function () { //onSubmit
                updateEditor();

                $.post(urlPostAction, $("#ApproveForm").mySerialize(), function (data) {
                    if (data.Erros)
                        createMessage("Đã có lỗi xảy ra", data.Message); // Tạo thông báo lỗi
                    else {
                        $("#dialog-form").dialog('close'); //Đóng form thêm mới - sửa
                        createCloseMessage("Thông báo", data.Message, '#Page=1&itemId=' + data.ID + '&message=' + data.Message + '&temp=' + Math.floor(Math.random() * 11) + ''); // Tạo thông báo khi click đóng thì chuyển đến url đích
                    }
                });
                return false;
            }
        });

        $("#close").click(function () {
            $("#dialog-form").html("").dialog('close');
        });
    });
</script>

<form id="ApproveForm">
    @Html.AntiForgeryToken()<input type="hidden" name="do" id="do" value="approve" />
    <input type="hidden" name="ItemID" id="ItemID" value="@Model.ID" />
    <fieldset class="forms">
        <legend>Kiểm duyệt albumPicture ảnh</legend>
        <table class="tableforms" cellspacing="1" width="100%">

            <tr>
                <td colspan="2"><strong>Kiểm duyệt nội dung: @Model.Title @Model.Description</strong></td>
            </tr>
            <tr>
                <td style="width:80px;"><label>Trạng thái</label></td>
                <td>
                    <ul>
                        @foreach (var item in ViewBag.AllStatus)
                        {
                            if (Model.StatusID == item.ID)
                            {
                                <li style="float:left; margin-right:15px;"><input type="radio" name="StatusID" value="@item.ID" disabled /><span style="color:#AAA;">@item.Name</span></li>
                            }
                            else
                            {
                                <li style="float:left; margin-right:15px;"><input type="radio" name="StatusID" value="@item.ID" /><span>@item.Name</span></li>
                            }

                        }
                    </ul>
                </td>
            </tr>

            <tr>
                <td><label>Ghi chú</label></td>
                <td>
                    <textarea rows="3" id="Description" name="Description" spellcheck="false" style="height:50px !important;"></textarea>
                </td>
            </tr>
            <tr>
                <td>File đính kèm</td>
                <td>
                    <ul>
                       
                    </ul>
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>


            <tr>
                <td class="submit" colspan="2">
                    <button id="submit" type="submit" class="primaryAction">Thực hiện</button>
                    <button id="reset" type="reset" class="primaryAction">Nhập lại</button>
                    <button id="close" type="button" class="primaryAction">Đóng lại</button>
                </td>
            </tr>
        </table>
    </fieldset>

    <fieldset class="forms">
        <legend>Lịch sử kiểm duyệt albumPicture ảnh</legend>

        <table class="tableforms" cellspacing="1" width="100%">
            <tr>
                <th>Người thực hiện</th>
                <th>Thời gian thực hiện</th>
                <th>Trạng thái</th>
                <th>Ghi chú</th>
            </tr>
            @foreach (var item in Model.ApproveLogs)
            {
                <tr>
                    <td>@item.AspNetUser.UserName</td>
                    <td>@item.CreatedDate.ToString("dd/MM/yyyy hh:mm:ss tt")</td>
                    <td>@item.Status.Name</td>
                    <td>@item.Description</td>
                </tr>
            }
        </table>

    </fieldset>
</form>

Source/QNews.Admin/Views/AlbumPicture/AjaxForm.cshtml
@model QNews.Base.AlbumPicture
@{
    ViewBag.Title = ViewBag.ActionText + " albumPicture ảnh";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}
<script type="text/javascript">
    $(function () {

        createCKFider('Image', 120);

        $("#AlbumPictureForm").validate({
            rules: {
                Title:
                {
                    required: true,
                    minlength: 2,
                    maxlength: 255
                },
                Description:
                {
                    maxlength: 1000
                }
            },
            submitHandler: function () { //onSubmit
                updateEditor();

                $.post(urlPostAction, $("#AlbumPictureForm").mySerialize(), function (data) {
                    if (data.Erros)
                        createMessage("Đã có lỗi xảy ra", data.Message); // Tạo thông báo lỗi
                    else {
                        $("#dialog-form").dialog('close'); //Đóng form thêm mới - sửa
                        createCloseMessage("Thông báo", data.Message, '#Page=1&itemId=' + data.ID + '&message=' + data.Message + '&temp=' + Math.floor(Math.random() * 11) + ''); // Tạo thông báo khi click đóng thì chuyển đến url đích
                    }
                });
                return false;
            }
        });

        $("#close").click(function () {
            $("#dialog-form").html("").dialog('close');
        });

        $("select.fullwidthForm").select2({ width: '100%' });
    });
</script>

<form id="AlbumPictureForm">
    @Html.AntiForgeryToken()<input type="hidden" name="do" id="do" value="@ViewBag.Action" />
    <input type="hidden" name="ItemID" id="ItemID" value="@Model.ID" />
    <input type="hidden" id="listValueFileAttach" name="listValueFileAttach" />
    <input type="hidden" id="listValueFileAttachRemove" name="listValueFileAttachRemove" />
    <input type="hidden" name="TagValues" id="TagValues" />
    <input type="hidden" name="AlbumID" id="AlbumID" value="@Request["CategoryID"]" />
    <fieldset class="forms">
        <legend>Thông tin ảnh</legend>
        <table class="tableforms" cellspacing="1" width="100%">
            <tr>
                <td style="width:160px;"><label>Tên ảnh</label></td>
                <td>
                    <input type="text" name="Title" id="Title" value="@Model.Title" />
                </td>
            </tr>

            <tr>
                <td><label>Mô tả</label></td>
                <td>
                    <textarea rows="5" id="Description" name="Description" spellcheck="false">@Model.Description</textarea>
                </td>
            </tr>

            <tr>
                <td><label>Hình ảnh</label></td>
                <td>
                    <button id="ImageButton" type="button" class="primaryAction">Chọn hỉnh ảnh đại diện</button>
                    <br />
                    <i>Hoặc nhập đường link ảnh từ liên kết bên ngoài</i>
                    <br />
                    <input type="text" value="@((!string.IsNullOrEmpty(Model.Image) && Model.Image.Contains("http")) ? Model.Image : string.Empty)" name="OtherImage" id="OtherImage" />

                    <div id="ImageValues">
                        <input type="hidden" name="Image" value="@Model.Image" />
                        <img src="@(string.IsNullOrEmpty(Model.Image) ? "/Content/Admin/images/no_image.gif" : Model.Image)" style="border:1px solid #ccc; width:120px; margin-top:2px; float:left;" />
                        <button id="ImageButtonDelete" onclick="clearFKFider('Image', 120);" type="button" class="primaryAction" style="margin:25px 10px;">Xóa ảnh</button>
                    </div>
                </td>
            </tr>

            <tr>
                <td><label>Cho phép gửi bình luận</label></td>
                <td>
                    <input type="checkbox" name="AllowComment" id="AllowComment" value="True" @((Model.AllowComment) ? " checked" : string.Empty) />
                </td>
            </tr>


            <tr>
                <td><label>Lượt xem</label></td>
                <td>
                    <input type="text" value="@Model.Viewed" name="Viewed" id="Viewed" />
                </td>
            </tr>

            <tr>
                <td><label>Nguồn nội dung</label></td>
                <td>
                    <input type="text" value="@Model.Source" name="Source" id="Source" />
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>
            <tr>
                <td class="submit" colspan="2">
                    <button id="submit" type="submit" class="primaryAction">@ViewBag.ActionText</button>
                    <button id="reset" type="reset" class="primaryAction">Nhập lại</button>
                    <button id="close" type="button" class="primaryAction">Đóng lại</button>
                </td>
            </tr>
        </table>
    </fieldset>
</form>

Source/QNews.Admin/Views/AlbumPicture/AjaxView.cshtml
@model QNews.Base.AlbumPicture

@{
    ViewBag.Title = "Xem chi tiết";
    Layout = "~/Views/Shared/_Ajax.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#idTabs").idTabs();
    });
</script>
<fieldset class="forms">
    <table class="tableforms tabledetails" cellspacing="1" width="100%">
        <tr>
            <td style="width:160px;" class="label"><label>Tên ảnh</label></td>
            <td>
                @Html.DisplayFor(model => model.Title)
            </td>
        </tr>

        <tr>
            <td class="label"><label>Mô tả</label></td>
            <td>
                @Html.Raw(Model.Description)
            </td>
        </tr>

        <tr>
            <td class="label"><label>Ảnh đại diện</label></td>
            <td>
                <img src="@(string.IsNullOrEmpty(Model.Image) ? "/Content/Admin/images/no_image.gif?width=120" : Model.Image)" style="width:120px" />
            </td>
        </tr>

        <tr>
            <td class="label"><label>Cho phép gửi bình luận</label></td>
            <td>
                @Grid.DisplayShow(Model.Title, Model.AllowComment)
            </td>
        </tr>

        <tr>
            <td class="label"><label>Lượt xem</label></td>
            <td>
                @Model.Viewed
            </td>
        </tr>

        <tr>
            <td class="label"><label>Người tạo</label></td>
            <td>@Model.AspNetUser_CreateBy.UserName</td>
        </tr>

        <tr>
            <td class="label"><label>Ngày tạo</label></td>
            <td>@Model.CreateDate.ToString("dd/MM/yyyy hh:mm:ss tt")</td>
        </tr>

        <tr>
            <td class="label"><label>Người sửa cuối</label></td>
            <td>@Model.AspNetUser_ModifyBy.UserName</td>
        </tr>

        <tr>
            <td class="label"><label>Ngày sửa</label></td>
            <td>@Model.ModifyDate.ToString("dd/MM/yyyy hh:mm:ss tt")</td>
        </tr>
    </table>
</fieldset>

Source/QNews.Admin/Views/AlbumPicture/Index.cshtml
@{
    ViewBag.Title = "Quản lý albumPicture ảnh";
    bool hasAdd = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Add");
    bool hasEdit = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Edit");
    bool hasDelete = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Delete");
    bool hasApprove = HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("Approve");
}
}
<script type="text/javascript">

    urlLists = '@Url.Action("ListItems", "AlbumPicture")';
    urlForm = '@Url.Action("AjaxForm", "AlbumPicture")';
    urlFormApprove = '@Url.Action("AjaxApprove", "AlbumPicture")';
    urlPostAction = '@Url.Action("Actions", "AlbumPicture")';
    urlView = '@Url.Action("AjaxView", "AlbumPicture")';
    formWidth = 1100;
    formHeight = 650;
    viewWidth = 1100;
    viewHeight = 650;

    $(document).ready(function () {
        initAjaxLoad(urlLists, "#JobGriditems");

        $("#gridSearch").submit(function () {
            var form = $("#gridSearch");
            window.location.href = '#' + getValueFormMutilSelect(form);
            return false;
        });

        $("#btn_add").click(function () {
            $("#dialog-form").dialog(
				{
				    title: "Thêm mới albumPicture ảnh",
				    width: formWidth,
				    height: formHeight
				}
			).load(encodeURI(urlForm + "?do=Add")).dialog("open");
            return false;
        });

        $.datepicker.setDefaults($.datepicker.regional['vi']);
        $("#TuNgay").datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            onSelect: function (dateStr) {
                var min = $(this).datepicker('getDate') || new Date(); // Selected date or today if none
                $('#DenNgay').datepicker('option', { minDate: min });
            }
        });

        $("#DenNgay").datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            minDate: $("#TuNgay").val()
        });

        $("select.fullwidth").select2({ width: 605 });
    });

    function getVersion(versionId) {
        var tokenValid = $("input[name='__RequestVerificationToken']").val();
        $.post(urlPostAction, { "do": "reset", "ItemID": versionId, "__RequestVerificationToken": "" + tokenValid + "" }, function (data) {
            if (data.Erros)
                createMessage("Đã có lỗi xảy ra", data.Message); // Tạo thông báo lỗi
            else {
                $("#dialog-form").dialog('close'); //Đóng form thêm mới - sửa
                createCloseMessage("Thông báo", data.Message, '#Page=1&itemId=' + data.ID + '&message=' + data.Message + '&temp=' + Math.floor(Math.random() * 11) + ''); // Tạo thông báo khi click đóng thì chuyển đến url đích
            }
        });
    }

</script>
<div class="zone zone-content">
    <h1>Quản lý albumPicture ảnh</h1>
    
    <div class="headear">
        <div style="width: 700px; padding: 10px;" class="searchbox advance leftright">
            <form id="gridSearch">
                <fieldset class="bulk-actions">
                    <div class="row">
                        <div class="left">
                            <label for="Keyword">Từ khóa:</label>
                            <input type="text" name="Keyword" id="Keyword" value="Từ khóa tìm kiếm" onfocus="if(this.value=='Từ khóa tìm kiếm') this.value='';" onblur="if(this.value=='') this.value='Từ khóa tìm kiếm';" />
                        </div>
                        <div class="right">
                            <label for="SearchIn">Tìm trong:</label>
                            <select name="SearchIn" id="SearchIn" class="mutil" multiple="multiple">
                                <option value="Title" selected>Tên albumPicture ảnh</option>
                                <option value="Description">Mô tả</option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="left">
                            <label>Xuất bản:</label>
                            <span><i>Từ</i></span>
                            <input type="text" name="TuNgay" id="TuNgay" style="width:92px" />
                            <span><i>Đến</i></span>
                            <input type="text" name="DenNgay" id="DenNgay" style="width:91px" />
                        </div>

                        <div class="right">
                            <label>Trạng thái:</label>
                            <select name="StatusID">
                                <option value="">Tất cả</option>
                                @foreach (var item in ViewBag.AllStatus)
                                {
                                    <option value="@item.ID">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="left">
                            <label>Người tạo:</label>
                            <select name="CreateBy">
                                <option value="">Tất cả</option>
                                @foreach (var item in ViewBag.AllUser)
                                {
                                    <option value="@item.ID">@item.UserName</option>
                                }
                            </select>
                        </div>

                        <div class="right">
                            <label>Sửa cuối:</label>
                            <select name="ModifyBy">
                                <option value="">Tất cả</option>
                                @foreach (var item in ViewBag.AllUser)
                                {
                                    <option value="@item.ID">@item.UserName</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <label>Album ảnh</label>
                        <select name="TopicID" class="fullwidth">
                            <option value="">Tất cả</option>
                            @foreach (var item in ViewBag.AllCategory)
                            {
                                <option value="@item.ID">@item.Title</option>
                            }
                        </select>
                    </div>
                    <div class="row">
                        <div class="submit">
                            <button name="submit.Search" type="submit">Tìm kiếm</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>

        <div class="manage">
            @if (hasAdd)
            {
                @Html.ActionLink("Thêm mới", "Create", new { }, new { @class = "add button primaryAction", @id = "btn_add" })
            }
        </div>
    </div>
    
    <div id="JobGriditems">
    
    </div>
</div>